id: P009591
initial_creation_type: ocr
source_metadata:
  id: bdr:W4PD1180
  title: ཡི་དམ་དགོངས་འདུས།༼པར་རྙིང་།༽
  author: ''
  volumes:
    931f914933c9446b9c37936e020d40da:
      image_group_id: I2PD19821
      title: ''
      volume_number: 1
      total_pages: 588
    f0c42a74c2364bb2aebfd6dfd5113e47:
      image_group_id: I2PD19822
      title: ''
      volume_number: 2
      total_pages: 670
    e6728d373fcf4035b8e5a027ea0a0ee4:
      image_group_id: I2PD19823
      title: ''
      volume_number: 3
      total_pages: 504
    ec1873dad816402281fa633c496c5516:
      image_group_id: I2PD19824
      title: ''
      volume_number: 4
      total_pages: 782
    5ff4e6940ac44a8ab98f3a9118f478d6:
      image_group_id: I2PD19825
      title: ''
      volume_number: 5
      total_pages: 612
    d7b3c9daa6fe43a6be4085646448cd8c:
      image_group_id: I2PD19826
      title: ''
      volume_number: 6
      total_pages: 584
    a7dec65a458049f78db6362484008c6b:
      image_group_id: I2PD19827
      title: ''
      volume_number: 7
      total_pages: 604
    5f599570bdce4bfd8f060bfe3ab699e4:
      image_group_id: I2PD19828
      title: ''
      volume_number: 8
      total_pages: 640
    001a844816b64d4d884f52e76a500896:
      image_group_id: I2PD19829
      title: ''
      volume_number: 9
      total_pages: 722
    ff0ba68c8d6440928ba73ae2d1f08dce:
      image_group_id: I2PD19830
      title: ''
      volume_number: 10
      total_pages: 612
    62f6833e879148cd9228202a651bb442:
      image_group_id: I2PD19831
      title: ''
      volume_number: 11
      total_pages: 574
    f92c87edede0470e8eba14f3712cbb7d:
      image_group_id: I2PD19832
      title: ''
      volume_number: 12
      total_pages: 592
