id: I8D4F82CD
legacy_id: P009591
ocr_import_info:
  bdrc_scan_id: W4PD1180
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T15:55:56'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T21:13:00.664879+00:00'
last_modified: 2022-09-04 05:15:33.882248
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W4PD1180
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW4PD1180
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཡི་དམ་དགོངས་འདུས།༼པར་རྙིང་།༽
  author: ནུས་ལྡན་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.535334272486975
  ocr_word_median_confidence_index: 0.5400000214576721
quality: null
bases:
  I2PD19827:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD19827
      total_pages: 604
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I2PD19827.txt
    statistics:
      ocr_word_median_confidence_index: 0.5299999713897705
      ocr_word_mean_confidence_index: 0.5249649729082505
    legacy_id: v007
  I2PD19824:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD19824
      total_pages: 782
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I2PD19824.txt
    statistics:
      ocr_word_median_confidence_index: 0.5600000023841858
      ocr_word_mean_confidence_index: 0.5482429184124487
    legacy_id: v004
  I2PD19831:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD19831
      total_pages: 574
      volume_number: 11
      volume_pages_bdrc_intro: 2
    order: 11
    base_file: I2PD19831.txt
    statistics:
      ocr_word_median_confidence_index: 0.5400000214576721
      ocr_word_mean_confidence_index: 0.5298408570408919
    legacy_id: v011
  I2PD19830:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD19830
      total_pages: 612
      volume_number: 10
      volume_pages_bdrc_intro: 2
    order: 10
    base_file: I2PD19830.txt
    statistics:
      ocr_word_median_confidence_index: 0.46000000834465027
      ocr_word_mean_confidence_index: 0.4832254933595985
    legacy_id: v010
  I2PD19825:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD19825
      total_pages: 612
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I2PD19825.txt
    statistics:
      ocr_word_median_confidence_index: 0.5099999904632568
      ocr_word_mean_confidence_index: 0.5117995353508673
    legacy_id: v005
  I2PD19823:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD19823
      total_pages: 504
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I2PD19823.txt
    statistics:
      ocr_word_median_confidence_index: 0.550000011920929
      ocr_word_mean_confidence_index: 0.5366454886546197
    legacy_id: v003
  I2PD19832:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD19832
      total_pages: 592
      volume_number: 12
      volume_pages_bdrc_intro: 2
    order: 12
    base_file: I2PD19832.txt
    statistics:
      ocr_word_median_confidence_index: 0.550000011920929
      ocr_word_mean_confidence_index: 0.5404010679645946
    legacy_id: v012
  I2PD19826:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD19826
      total_pages: 584
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I2PD19826.txt
    statistics:
      ocr_word_median_confidence_index: 0.5099999904632568
      ocr_word_mean_confidence_index: 0.5151838752230274
    legacy_id: v006
  I2PD19829:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD19829
      total_pages: 722
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I2PD19829.txt
    statistics:
      ocr_word_median_confidence_index: 0.5199999809265137
      ocr_word_mean_confidence_index: 0.5189581390366902
    legacy_id: v009
  I2PD19821:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD19821
      total_pages: 588
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2PD19821.txt
    statistics:
      ocr_word_median_confidence_index: 0.6499999761581421
      ocr_word_mean_confidence_index: 0.6035194777360173
    legacy_id: v001
  I2PD19828:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD19828
      total_pages: 640
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I2PD19828.txt
    statistics:
      ocr_word_median_confidence_index: 0.5699999928474426
      ocr_word_mean_confidence_index: 0.5492326110878506
    legacy_id: v008
  I2PD19822:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD19822
      total_pages: 670
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I2PD19822.txt
    statistics:
      ocr_word_median_confidence_index: 0.5899999737739563
      ocr_word_mean_confidence_index: 0.5627538316746981
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
