id: I8D4F82CD
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T16:00:45+00:00'
last_modified: '2022-06-08T12:06:55.626137+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4PD1180
  title: ཡི་དམ་དགོངས་འདུས།༼པར་རྙིང་།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '3764':
      image_group_id: I2PD19821
      title: ''
      total_pages: 588
      order: 1
      base_file: 3764.txt
    0B67:
      image_group_id: I2PD19822
      title: ''
      total_pages: 670
      order: 2
      base_file: 0B67.txt
    BC54:
      image_group_id: I2PD19823
      title: ''
      total_pages: 504
      order: 3
      base_file: BC54.txt
    128F:
      image_group_id: I2PD19824
      title: ''
      total_pages: 782
      order: 4
      base_file: 128F.txt
    6EC8:
      image_group_id: I2PD19825
      title: ''
      total_pages: 612
      order: 5
      base_file: 6EC8.txt
    00C3:
      image_group_id: I2PD19826
      title: ''
      total_pages: 584
      order: 6
      base_file: 00C3.txt
    7C24:
      image_group_id: I2PD19827
      title: ''
      total_pages: 604
      order: 7
      base_file: 7C24.txt
    AA41:
      image_group_id: I2PD19828
      title: ''
      total_pages: 640
      order: 8
      base_file: AA41.txt
    A593:
      image_group_id: I2PD19829
      title: ''
      total_pages: 722
      order: 9
      base_file: A593.txt
    CCB4:
      image_group_id: I2PD19830
      title: ''
      total_pages: 612
      order: 10
      base_file: CCB4.txt
    '4403':
      image_group_id: I2PD19831
      title: ''
      total_pages: 574
      order: 11
      base_file: 4403.txt
    6ADB:
      image_group_id: I2PD19832
      title: ''
      total_pages: 592
      order: 12
      base_file: 6ADB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
